name: 'object_store_test'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# ----------------------------
#  GLOBAL CONFIG
# ----------------------------
models:
  object_store_test:
    +materialized: view

# ----------------------------
#  SEED CONFIG
# ----------------------------
seeds:
  object_store_test:
    +quote_columns: false
    +column_types:
      personid: bigint
      npi: string
      startdate: timestamp
      enddate: timestamp
      sourcepartition: string
      rulenum: string
      visitdate: timestamp
      medicalind: int

    arcadia:  # aplica SOLO a seeds/arcadia/*
      +materialized: table

    
    providerperson:
        +column_types:
          _hoodie_commit_time: string
          _hoodie_commit_seqno: string
          _hoodie_record_key: string
          _hoodie_partition_path: string
          _hoodie_file_name: string
          providerpersonid: string
          lastname: string
          firstname: string
          provfullname: string
          npi: string
          specialty: string
          providerid: string
          sourceid: string
          activeind: string
          deleteind: string
          inserttimestamp: string
          updatetimestamp: string

