name: 'object_store_test'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# ----------------------------
#  GLOBAL CONFIG
# ----------------------------
models:
  object_store_test:
    +materialized: view

# ----------------------------
#  SEED CONFIG
# ----------------------------
seeds:
  object_store_test:
    +quote_columns: false
    +column_types:
      personid: bigint
      npi: string
      startdate: timestamp
      enddate: timestamp
      sourcepartition: string
      rulenum: string
      visitdate: timestamp
      medicalind: int

    arcadia:  # aplica SOLO a seeds/arcadia/*
      +materialized: table

    
    providerperson:
        +column_types:
          _hoodie_commit_time: string
          _hoodie_commit_seqno: string
          _hoodie_record_key: string
          _hoodie_partition_path: string
          _hoodie_file_name: string
          providerpersonid: string
          lastname: string
          firstname: string
          provfullname: string
          npi: string
          specialty: string
          providerid: string
          sourceid: string
          activeind: string
          deleteind: string
          inserttimestamp: string
          updatetimestamp: string
    
    plan_member:
        +column_types:
          _hoodie_commit_time: string
          _hoodie_commit_seqno: string
          _hoodie_record_key: string
          _hoodie_partition_path: string
          _hoodie_file_name: string
          member_id: string
          first_name: string
          middle_name: string
          last_name: string
          contact_title: string
          sex_unscrubbed: string
          home_phone: string
          business_phone: string
          cell_phone: string
          dob: string
          death_date: string
          head_of_household_name: string
          pregnancy_date: string
          first_covered_date: string
          special_needs_unscrubbed: string
          individual_no: string
          language_unscrubbed: string
          risk_unscrubbed: string
          marital_status_unscrubbed: string
          ssn: string
          relationship_unscrubbed: string
          ethnicity_unscrubbed: string
          medicaid_id: string
          medicare_id: string
          source_id: string
          create_timestamp: string
          modify_timestamp: string
          created_by: string
          modified_by: string
          delete_ind: string
          loaded_from_file: string
          medicaid_renewal_date: string
          race_unscrubbed: string
          ethnicity: string
          language: string
          marital_status: string
          race: string
          relationship: string
          sex: string
          special_needs: string
          risk: string
          scrubbed: string
          id: string
          member: string
          exportcategory: string
          deleted_reason: string
          quality_fail_reason: string
          row_hash: string
          extract_timeseries_bucket: string
          availability: string
          _arcadia_source: string
          year_bucket: string
          deleted: string
          lowquality: string
          transitioned: string
    
    patient:
        +column_types:
          center_id: string
          patient_id: string
          provider_id: string
          first_name: string
          middle_name: string
          last_name: string
          race: string
          ethnicity: string
          language: string
          email: string
          address1: string
          address2: string
          city: string
          county: string
          state: string
          zip: string
          phone: string
          birth_date: string
          death_date: string
          patient_status: string
          create_timestamp: string
          delete_ind: string
          sex: string
          modify_timestamp: string
          mrn: string
          loaded_from_file: string
          guarantor_self_ind: string
          guarantor_id: string
          homelessness_status: string
          migrant_status: string
          veteran_status: string
          ssn: string
          income: string
          family_size: string
          alias: string
          guarantor_relationship: string
          phone2: string
          advance_directive_ind: string
          billing_account_id: string
          usual_location: string
          opt_in_ind: string
          mail_address1: string
          mail_address2: string
          mail_city: string
          mail_state: string
          mail_zip: string
          medicaid_id: string
          occupation: string
          race_scrubbed: string
          language_scrubbed: string
          ethnicity_scrubbed: string
          patient_status_scrubbed: string
          test_patient_ind: string
          scrubbed: string
          outreach_opt_out: string
          id: string
          patient: string
          exportcategory: string
          deleted_reason: string
          quality_fail_reason: string
          row_hash: string
          extract_timeseries_bucket: string
          availability: string
          _arcadia_source: string
          year_bucket: string
          deleted: string
          lowquality: string
          transitioned: string
