default:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark          # nombre del servicio en docker-compose
      port: 10000
      schema: default      # db/schema
      database: default
      auth: NONE           # sin auth
      user: ""             # usuario vacío
      password: ""
      threads: 4
      connect_timeout: 60
      retries: 5